name: Compile Test

on: 
  pull_request:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      
    steps:
      - name: Checkout JavaCore
        uses: actions/checkout@v2
        with:
          repository: 'CoagulateSL/JavaCore'
          path: JavaCore
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'        
      - name: Build with Maven
        env: 
          PACKAGE_READ: ${{ secrets.PACKAGE_READ }}
        working-directory: JavaCore
        run: mvn --batch-mode clean compile
      - name: Checkout depender SLCore
        uses: actions/checkout@v2
        with:
          repository: 'CoagulateSL/SLCore'        
          path: SLCore
          token: ${{ secrets.PACKAGE_READ }}
          submodules: true
      - name: Git Submodule Update
        run: |
          cd SLCore
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Commit update
        working-directory: SLCore
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/CoagulateSL/SLCore
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
        
        
        
